### PR TITLE
bulk_fill_hanzi: Fix crash on Hanzi not present in dictionary

### LINKED ISSUE #34: bulk_fill_hanzi: throws exception if contents of Hanzi field not present in dictionary
I was filling in some new cards and received the following error. Not sure what card it fails on:

**Specs (please complete the following information):**
 - OS: [e.g. Windows, iOS, Ubuntu]: Mac 10.14.2
 - Anki Version [e.g. v2.0.52, v2.1.5]: 2.1.7
- Chinese Support Version [e.g. v0.5.3-beta] v0.9.1

**Additional context**

```
Anki 2.1.7 (a6c34fd7) Python 3.6.7 Qt 5.12.0 PyQt 5.11.3
Platform: Mac 10.14.2
Flags: frz=True ao=True sv=1

Caught exception:
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/fill.py", line 385, in bulk_fill_hanzi
    note.flush()
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/877182321/enhancedMain.py", line 694, in noteFlush
    oldNoteFluh(note,mod=mod)
  File "anki/notes.py", line 51, in flush
  File "anki/notes.py", line 69, in joinedFields
  File "anki/utils.py", line 265, in joinFields
<class 'TypeError'>: sequence item 6: expected str instance, NoneType found
```

### PR DESCRIPTION
**Pull request by telotortium**
Fix #34

### CODE REVIEW

**Comment by telotortium** [comment]
It would be great to add a test to ensure that this bug doesn't pop up again, at least for the character on which it crashed, `'𠂉'`. Where would be the best place to put such a test?

**Comment by luoliyan** [comment]
If you want to start a `test_fill.py` file, that would be great. You can just use one of the other files as a template.

**Comment by telotortium** [comment]
Hmm, it looks like the `bulk_fill_hanzi` and related functions directly query Anki's database, using the `Finder` class. Do you have any opinions on how you want to test interactions with Anki's code? It appears that [Anki's documentation](https://apps.ankiweb.net/docs/addons.html) doesn't mention it at all. I'd probably just stub out any Anki code that `bulk_fill_hanzi` needs, by making a `StubFinder` class or similar.

**Comment by telotortium** [comment]
I've just ended up adding unit tests for the `fill_simp` and `fill_trad` methods.

**Pull request merged**
