### PR TITLE
English Usage Sentences Implementation, gtts, requirements, color Traditional/Cantonese, readme, debug file

### PR DESCRIPTION
**Pull request by joeminicucci**
- Added gtts 2.2.1 lib
- Updated requirements.txt
- Updated README with Pycharm debug instructions
- Added simple Pycharm debug run file for ease of debugging

### CODE REVIEW

**Comment by zacbennett** [comment]
Sorry, first time at looking at a PR for an anki add on. Why don't we have gTTS as a python package specified in requirements.txt? Copying and pasting the updated package is prone to human error.

**Comment by joeminicucci** [comment]
@zacbennett This is how it is already implemented. Adding it in as a static dependency does introduce upward compatibility issues with Google in the future, but it also ensures that end-users do not have to do any development installations when they install the plugin, i.e. it is 'plug and play'.

**Comment by joeminicucci** [comment]
Also, this removes the unnecessary token library by virtue of upstream refactoring on the gtts source code. If you want to see how this can effect users without a static dependency, simply clone the repo, remove the existing gtts lib folder (its already like this on master), add it to requirements and notice that Anki does not auto-resolve the requirements.txt pip dependencies for end-users.

**Comment by joeminicucci** [comment]
###  English Usage Sentences Implementation

- db update script bug fixes, refactoring
- db update script corpora pulling
- db update script zip file backups
- db update script dictionary sources updates
- Unit test updates
- Card filling - non-scalar values have verbose, copy-able output dialogs with failed hanzi
- db.zip data backup

**ALL TESTS PASSING**

**Comment by linguax-gc** [comment]
That sounds great @joeminicucci, hope it gets merged soon! Would it be possible to add an option to fill monolingual dictionary definitions? Afaik, zdic.net definitions are in the public domain (https://www.zdic.net/aboutus/copyright/). That would be an amazing feature to add alongside Tatoeba sample sentences.

Thanks again!

**Comment by linguax-gc** [comment]
@joeminicucci Hey, so tried it installing your version and it works great! Thanks! I was wondering if the examples it gets come from self-identified natives in Tatoeba and are not orphans.

Only problem I found is that I cannot seem to modify the number of examples. I changed it to 3 in the config.json (and it appears as 3 in the configuration file inside Anki), but it keeps giving me 10 examples for everything. Also, when it's done, the message showing which cards failed doesn't actually show the cards that failed, only the message: 
```
Usages may not be available in the database's data set. Custom data can be added to the english_usage column in thechinese.db database.
The following notes failed:
``` 
As an aside, it would be amazing if the user could set the language of the examples instead of being limited to English.

In any case, thank you so much! Have a good end of the year!

**Comment by joeminicucci** [comment]
@linguax-gc 
**Languages**
The intention is to use bi-lingual corporas, but it is definitely possible to add other languages very easily by changing the language codes in the call to tatoeba downloads. 
If you are looking for simple Chinese sentences, there are hundreds of thousands of more in that tatoeba dataset that are either oprhaned or used by a different language. Simply take out the call to merge the corporas and modify the fill logic a bit and you can make that work, if that's what you want. I'm not sure what you are suggesting in terms of the monolingual dictionary additions, but appreciate the download link.

**Modification Number error**

This is actually due to the plugins behavior to cache the config.json file as config_saved.json. Simply delete the config_saved.json to fix your problem and have the plugin obey the max sentences again.

**Comment by linguax-gc** [comment]
**Languages**
I see. Well, I'll try to have a look when I can. I know next to nothing about programming, databases and calls, etc. So I might have to do some research. I think having options to select whether the user wants translations or not and in which languages would be very useful. Regarding orphan and non-native sentences, I just think those might have some mistakes and that's why I would prefer to avoid them. But I understand there are many more. 

**Monolingual dictionary**
I meant extracting definitions from monolingual dictionaries, instead of translations from bilingual ones. I believe at some point it is useful to have monolingual definitions instead (or along) translations. In any case I found out this can be done with the Migaku Dictionary [addon](https://github.com/migaku-official/Migaku-Dictionary-Addon). It seems to fall within the scope of this addon as well though.

**Modification Number Error**
Cool, yes, that worked.

**GUI Error**
I just tried again and now the failed notes appear, but the whole Anki is frozen in "Processing". Here's an extract of the collection to keep it small. Same problem. Maybe I have something installed that's breaking something... It seems I can't get any examples now since Anki is frozen and have to force close it.
[collection.zip](https://github.com/luoliyan/chinese-support-redux/files/5757536/collection.zip)

新年快乐！

**Comment by joeminicucci** [comment]
GUI bug fix submitted, and PR ready. **Tests still 100%**

**Comment by joeminicucci** [comment]
Additions of Traditional / Cantonese Color added to the behavior / fill logic

**Comment by srghma** [comment]
there is a deprecation warning

```
Finder() is deprecated, please use col.find_cards() or .find_notes()
```

**Comment by joeminicucci** [comment]
> 
> 
> there is a deprecation warning `Version ⁨2.1.36 (c505894b)⁩`
> 
> ```
> Finder() is deprecated, please use col.find_cards() or .find_notes()
> ```

Pretty sure that applies pre-pull request as I didn't modify the core Anki deck lib calls

**Pull request merged**
